Repository nuxt-community/vuetify-module, pull requests merged in 2019-08, with the labels that each got.

#99 feat: optionsPath + function behavior
  README.md
  lib/module.js
  lib/templates/plugin.js
  test/fixture/nuxt.config.js
  test/fixture/vuetify.options.js
Labels: feature request

#110 feat: manual import
  lib/templates/plugin.js
  test/fixture/pages/manual-import.vue
  test/module.test.js
Labels: feature

#119 feat(types): provide nuxt 2.9 compatible types
  types/index.d.ts
Labels: enhancement

#139 chore(deps): update dependency sass-loader to v8
  lib/module.js
  package.json
  test/module.test.js
  yarn.lock
Labels: dependencies

#138 fix: remove duplicate import of main.sass
  lib/module.js
Labels: fix
