Repository nuxt-community/vuetify-module, pull requests merged in 2020-01, with the labels that each got.

#237 Bump vuetify version to latest and fix type path
  package.json
  src/options.ts
  yarn.lock
Labels: dependencies, fix

#234 docs: add some small details about fonts
  README.md
Labels: documentation

#239 fix: replace treeShake with globalImports
  src/plugin.ts
  templates/plugin.js
Labels: fix

#273 fix: fix VuetifyLoaderOptions match type
  src/options.ts
  test/module.test.ts
Labels: fix

#267 fix: use minimal vuetify import
  templates/plugin.js
Labels: fix
